[llama_cloud]
api_key = "llx-Y6cRshsPPvh9hyGwvkPYXN0iPocYXo7H4PlZnMPY0hASzDSu"

[azure_openai]
api_key = "3xPDwbMLxnRrhsGke6eymlGOr4poo5h3jmHH5jZgZRzFuw1kwLXTJQQJ99AJACYeBjFXJ3w3AAABACOGiocA"
endpoint = "https://us-tax-law-rag-demo.openai.azure.com/"
deployment = "gpt-4o-mini"
api_version = "2024-08-01-preview"

[mongo]
uri = "mongodb+srv://utkarshsingh:G8stmYP7mbRXp3zR@clusterforresumes.trfczld.mongodb.net/"
db_name = "resume_db"
collection_name = "resumes"


